## Type by me

In [2]:
# joblib is used to save a model

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import joblib 
import os

plt.style.use('fivethirtyeight')

In [57]:
#eta is learning rate and  epochs iteration and 1e-4 is used to minimize  the weight

#we use a very small weights bcoz this will help you to converge the pass ,if you keep weights very large i.e your weight update will take longer time

class perceptron:
    def __init__(self , eta : float=None , epochs : int=None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta    #Learning Rate
        self.epochs = epochs    #Iteration
    
    def _z_outcome(self , inputs , weights):
        return np.dot(inputs,weights)
        
    def activation_function(self , z):
        return np.where(z > 0 , 1 ,0)    #if z is greater than 0 then put 1 other wise 0
    
    def fit(self , x , y):
        self.x = x
        self.y = y
        
        x_with_bias =  np.c_[self.x , -np.ones((len(self.x) , 1))]       # x is concatanact with x(not) based on theory (4,1)
        print(f"x_with_bias : \n{x_with_bias}")
        
         
        for epochs in range(self.epochs):
            
            
            z = self._z_outcome(x_with_bias,self.weights)
            y_hats = self.activation_function(z)
            print(f"predicted value after forward pass: \n{y_hats}")
            
            self.error = self.y - y_hats
            print(f"error: \n{self.error}")
            
            self.weights = self.weights + self.eta * np.dot(x_with_bias.T , self.error )
            print(f"updated weights after epoch: {epochs + 1}/{self.epochs}: \n{self.weights}")
            print(f"##"*10)
            
            
    def predict(self, X):
        x_with_bias = np.c_[x, -np.ones((len(x), 1))]
        z = self._z_outcome(x, self.weights)
        return self.activation_function(z)
    



            
            

In [58]:
OR = {
    'x1' : [0,0,1,1],
    'x2' : [0,1,0,1],
    'y'  : [0,1,1,1]
}

df_or_gate = pd.DataFrame(OR)
df_or_gate

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [59]:
def prepare_data(df , target_coloumn = 'y'):
    x = df.drop(target_coloumn , axis = 1)      #axis=1 for coloumn
    y = df[target_coloumn]
    
    return x , y

In [60]:
x , y = prepare_data(df_or_gate) # Check function
x

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [61]:
x , y = prepare_data(df_or_gate)

ETA = 0.1
EPOCHS = 10

model_or = perceptron(eta= ETA , epochs=EPOCHS)
model_or.fit(x,y)

x_with_bias : 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    1
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[ 0.19995084  0.1998538  -0.29995378]
####################
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[ 0.19995084  0.1998538  -0.19995378]
####################
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[ 0.19995084  0.1998538  -0.09995378]
####################
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 4/10: 
[1.99950842e-01 1.99853804e-01 4.62240753e-05]
####################
predicted value after forward pass: 
[0 1 1 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated we

## By class

In [66]:
class Perceptron:
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta # learning rate
        self.epochs = epochs # iterations
        
    def _z_outcome(self, inputs, weights):
        return np.dot(inputs, weights)
    
    def activation_function(self, z):
        return np.where(z > 0, 1, 0)
        
    def fit(self, X, y):
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))]
        print(f"X with bias: \n{X_with_bias}")
        
        for epoch in range(self.epochs):
            print("--"*10)
            print(f"for epoch >> {epoch + 1}")
            print("--"*10)
            
            z = self._z_outcome(X_with_bias, self.weights)
            y_hat = self.activation_function(z)
            print(f"predicted value after forward pass: \n{y_hat}")
            
            self.error = self.y - y_hat
            print(f"error: \n{self.error}")
            
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T, self.error)
            print(f"updated weights after epoch: {epoch + 1}/{self.epochs}: \n{self.weights}")
            print(f"##"*10)
            
            
    def predict(self, X):
        X_with_bias = np.c_[X, -np.ones((len(X), 1))]
        z = self._z_outcome(X_with_bias, self.weights)
        return self.activation_function(z)
    
    
    

In [76]:
OR = {
    'x1' : [0,0,1,1],
    'x2' : [0,1,0,1],
    'y'  : [0,1,1,1]
}

df_or_gate = pd.DataFrame(OR)
df_or_gate

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [72]:
def prepare_data(df , target_coloumn = 'y'):
    X = df.drop(target_coloumn , axis = 1)      #axis=1 for coloumn
    y = df[target_coloumn]
    
    return X , y

In [73]:
X , y = prepare_data(df_or_gate)

ETA = 0.1
EPOCHS = 10

model_or = perceptron(eta= ETA , epochs=EPOCHS)
model_or.fit(X,y)

x_with_bias : 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
predicted value after forward pass: 
[0 0 0 1]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[ 0.10004274  0.10003194 -0.1999276 ]
####################
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[ 0.10004274  0.10003194 -0.0999276 ]
####################
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[1.00042739e-01 1.00031939e-01 7.24036565e-05]
####################
predicted value after forward pass: 
[0 1 1 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 4/10: 
[1.00042739e-01 1.00031939e-01 7.24036565e-05]
####################
predicted value after forward pass: 
[0 1 1 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
u

In [79]:
AND  = { 'x1' : [0,0,1,1],
         'x2' : [0,1,0,1],
          'y' : [0,0,0,1]
    
}

df_and_gate = pd.DataFrame(AND)
df_and_gate

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [81]:
X , y = prepare_data(df_and_gate)
ETA = 0.1
EPOCHS = 10

model_or = perceptron(eta= ETA , epochs=EPOCHS)
model_or.fit(X,y)

x_with_bias : 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[-0.09990721 -0.10000497  0.29997241]
####################
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[ 9.27895480e-05 -4.96577237e-06  1.99972408e-01]
####################
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[0.10009279 0.09999503 0.09997241]
####################
predicted value after forward pass: 
[0 1 1 1]
error: 
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch: 4/10: 
[ 9.27895480e-05 -4.96577237e-06  2.99972408e-01]
####################
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int6

In [84]:
Ex_or ={
    'x1' : [0,0,1,1],
    'x2' : [0,1,0,1],
    'y' : [0,1,1,0]
}

df_ex_or_gate = pd.DataFrame(Ex_or)

X , y = prepare_data(df_ex_or_gate)
ETA = 0.1
EPOCHS = 50

model_or = perceptron(eta= ETA , epochs=EPOCHS)
model_or.fit(X,y)


x_with_bias : 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights after epoch: 1/50: 
[-0.0999576  -0.09999262  0.19988479]
####################
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights after epoch: 2/50: 
[ 4.24019532e-05  7.37866172e-06 -1.15213142e-04]
####################
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights after epoch: 3/50: 
[-0.0999576  -0.09999262  0.19988479]
####################
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights after epoch: 4/50: 
[ 4.24019532e-05  7.37866172e-06 -1.15213142e-04]
####################
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: i